# Generated by Django 5.1.7 on 2025-06-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_dailymenu_weeklymenu_dailyanalysis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='photo_day',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
