# Generated by Django 5.0.14 on 2025-06-09 16:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_count', models.IntegerField(default=0)),
                ('no_waste_count', models.IntegerField(default=0)),
                ('total_analysis', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='analysisresult',
            old_name='soup_type',
            new_name='food_type',
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='analysis_date',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='food_category',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
