# Generated by Django 5.1.7 on 2025-04-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysisresult',
            old_name='soup_type',
            new_name='food_type',
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='food_category',
            field=models.CharField(default='corba', max_length=50),
            preserve_default=False,
        ),
    ]
