# Generated by Django 5.1.7 on 2025-06-02 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_soup_type_analysisresult_food_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('soup', models.CharField(max_length=100)),
                ('main_dish', models.CharField(max_length=255)),
                ('side_dish', models.CharField(max_length=255)),
                ('extra', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_count', models.IntegerField(default=0)),
                ('no_waste_count', models.IntegerField(default=0)),
                ('total_analysis', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('daily_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='users.dailymenu')),
            ],
        ),
        migrations.AddField(
            model_name='dailymenu',
            name='weekly_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_menus', to='users.weeklymenu'),
        ),
    ]
