# Generated by Django 5.1.7 on 2025-06-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_analysisresult_photo_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymenu',
            name='main_dish_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dailymenu',
            name='side_dish_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
