# Generated by Django 5.0.14 on 2025-06-08 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_dailymenu_main_dish_2_dailymenu_side_dish_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailymenu',
            name='weekly_menu',
        ),
        migrations.RemoveField(
            model_name='dailyanalysis',
            name='daily_menu',
        ),
        migrations.RemoveField(
            model_name='analysisresult',
            name='image_url',
        ),
        migrations.DeleteModel(
            name='WeeklyMenu',
        ),
        migrations.DeleteModel(
            name='DailyMenu',
        ),
    ]
