# Generated by Django 5.0.14 on 2025-06-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_dailymenu_weekly_menu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
